import nodemailer from 'nodemailer';
import { SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS } from '../config/env';

export class EmailService {
    private transporter;

    constructor() {
        this.transporter = nodemailer.createTransport({
            host: SMTP_HOST,
            port: SMTP_PORT,
            secure: SMTP_PORT === 465, // true for 465, false for other ports
            auth: {
                user: SMTP_USER,
                pass: SMTP_PASS,
            },
        });
    }

    async sendEmail(to: string, subject: string, html: string) {
        console.log('--- Email Debug Info ---');
        console.log('SMTP_HOST:', SMTP_HOST);
        console.log('SMTP_PORT:', SMTP_PORT);
        console.log('SMTP_USER:', SMTP_USER ? '(Present)' : '(Missing)');
        // Mask password in logs
        console.log('SMTP_PASS:', SMTP_PASS ? '(Present)' : '(Missing)');
        console.log('------------------------');

        if (!SMTP_USER || !SMTP_PASS) {
            console.error('ERROR: SMTP credentials are explicitly missing in env variables.');
            throw new Error('Server email configuration is missing (SMTP_USER or SMTP_PASS). Check backend terminal logs.');
        }

        try {
            const info = await this.transporter.sendMail({
                from: `"${process.env.APP_NAME || 'Mindsphere'}" <${SMTP_USER}>`,
                to,
                subject,
                html,
            });
            console.log('Message sent: %s', info.messageId);
            return info;
        } catch (error) {
            console.error('Error sending email:', error);
            throw error;
        }
    }

    async sendWeeklyReport(to: string, userName: string, score: number, savedMins: number) {
        const subject = '🧠 Your Weekly MindSphere Insight';
        const html = `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #4F46E5;">Weekly Insight</h2>
            <p>Hi ${userName},</p>
            <p>Great job this week! You've been reclaiming your time.</p>
            
            <div style="background-color: #F3F4F6; padding: 20px; border-radius: 10px; margin: 20px 0;">
              <h3 style="margin: 0;">Stats Summary</h3>
              <ul style="list-style: none; padding: 0;">
                <li style="margin: 10px 0;">🛑 <strong>Doomscrolling Avoided:</strong> ${savedMins} mins</li>
                <li style="margin: 10px 0;">📈 <strong>Engagement Score:</strong> ${score}/100</li>
              </ul>
            </div>

            <p>Keep up the momentum!</p>
            <a href="${process.env.VITE_API_URL || 'http://localhost:5173'}/analytics" style="background-color: #4F46E5; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block;">View Full Report</a>
          </div>
        `;

        try {
            await this.sendEmail(to, subject, html);
            return true;
        } catch (error) {
            return false;
        }
    }
    async sendVideoRecommendations(to: string, userName: string, videos: any[]) {
        const subject = '📺 Your Personalized Video Picks';

        const videoItems = videos.map(v => `
            <div style="margin-bottom: 20px; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
                ${v.thumbnailUrl ? `<img src="${v.thumbnailUrl}" alt="${v.title}" style="width: 100%; height: auto; display: block;" />` : ''}
                <div style="padding: 15px;">
                    <h3 style="margin: 0 0 10px 0; font-size: 18px;">${v.title}</h3>
                    <p style="margin: 0 0 10px 0; color: #6b7280; font-size: 14px;">${v.description || 'Watch this video based on your interests.'}</p>
                    <a href="${v.url || '#'}" style="display: inline-block; background-color: #EF4444; color: white; padding: 8px 16px; text-decoration: none; border-radius: 4px; font-weight: bold;">Watch Now</a>
                </div>
            </div>
        `).join('');

        const html = `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #111827;">Your Weekly Watchlist</h2>
            <p>Hi ${userName},</p>
            <p>Based on your recent activity, we think you'll love these videos:</p>
            
            <div style="margin-top: 20px;">
                ${videoItems}
            </div>

            <p style="margin-top: 30px; color: #6b7280; font-size: 12px;">
                Generated by MindSphere Recommendation Engine
            </p>
          </div>
        `;

        try {
            await this.sendEmail(to, subject, html);
            return true;
        } catch (error) {
            return false;
        }
    }
}
